name: Debian Package Checker

on:
  workflow_dispatch:
    inputs:
      nama_paket:
        description: 'Masukkan nama paket yang ingin dicek (pisahkan dengan spasi, contoh: clang-21 llvm-21 gcc)'
        required: true
        default: 'clang'
        type: string

jobs:
  check-package:
    name: "Cek: ${{ github.event.inputs.nama_paket }}"
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
    - name: Update Paket Repositori
      run: |
        apt-get update

    - name: Cek Ketersediaan Paket di Debian Trixie
      run: |
        for paket in ${{ github.event.inputs.nama_paket }}; do
          echo "=================================================="
          echo " Memeriksa paket: $paket"
          echo "=================================================="
          
          apt-cache policy $paket || echo "❌ Paket '$paket' tidak ditemukan di repositori Debian Trixie."
          
          echo -e "\n"
        done
