name: Test Debian Trixie Apt Clang

on:
  workflow_dispatch:

jobs:
  test-env:
    runs-on: ubuntu-latest
    
    container:
      image: debian:trixie

    steps:
    - name: Update Paket Sistem
      run: |
        apt-get update

    - name: Install Clang
      run: |
        apt-get install -y clang

    - name: Cek Versi Clang
      run: |
        echo "=== MENAMPILKAN VERSI CLANG ==="
        clang -v
